### PR TITLE
Added lint job for Travis CI

### LINKED ISSUE #25: Add lint job on CI
Add lint job in our Travis CI

Travis CI documentation:

https://docs.travis-ci.com/

### PR DESCRIPTION
**Pull request by sudiptog81**
**CHANGELOG** :memo:

Adds linting step in the CI, before the build job gets triggered. Closes #25.

**LABELS**

* enhancement

_**NOTE:** Builds before merging #23 will fail._

### CODE REVIEW

**Comment by pyymenta** [comment]
@sudiptog81 

Thank you for your contribuition!

We have a trouble here, build is broken:

image


Any idea to fix it?

**Comment by sudiptog81** [comment]
The build needs to be triggered again.

**Comment by pyymenta** [comment]
@sudiptog81 you're right! I've retriggered the build

**Comment by pyymenta** [comment]
It Works, but we have some lint issues, could you fix It?

**Comment by sudiptog81** [comment]
Sure, have to modify the linting rules. Will rebase the PR and fix this in the next commit.

**Comment by sudiptog81** [comment]
The build passed!

**Review by pyymenta — APPROVED** [review]
Yeah! You did it! Great job!

**Pull request merged**
