### PR TITLE
ADDITION: Contributor Guidelines

### PR DESCRIPTION
**Pull request by AlenST**
**CHANGELOG** :memo:

* Added a separate file for Contributor Guidelines in order to eliminate any spam PRs and make quality Enhancements with regard to Issue #37 
* Added MIT License as per Issue #27

### CODE REVIEW

**Comment by pyymenta** [comment]
Thank your for your contribuition, sorry we already have the license file now.

**Comment by pyymenta** [comment]
Sorry, I'm accidenctaly closed your request :man_facepalming: 

If you remove the license section of your changes and fix the contributor-guidelies.md typo `guidelines`, I think your request will ready to be merged in

**Comment by AlenST** [comment]
Sure. I'll do that. :)
I'll take down this pull request and make the necessary changes required and send in another one :D
Thanks!

**Comment by pyymenta** [comment]
> Sure. I'll do that. :)
> I'll take down this pull request and make the necessary changes required and send in another one :D
> Thanks!

Also, you could keep this one open, just fixing those points, as you wish. What do you think?

**Comment by AlenST** [comment]
Sure, I'll do that! :D

**Comment by AlenST** [comment]
Changes made as per what you've asked, @pyymenta :)
Please do review it and let me know if anything is to be altered :D

**Comment by pyymenta** [comment]
> Changes made as per what you've asked, @pyymenta :)
> Please do review it and let me know if anything is to be altered :D

Oh you did it! Great job!

I think we need to link it in our README file, creating a new section for example. What do you think?

**Comment by AlenST** [comment]
Personally though, I'd keep the README file minimal just to give the user a glimpse to the Repo itself. But we could add a Link to the Guidelines?

**Comment by pyymenta** [comment]
> Personally though, I'd keep the README file minimal just to give the user a glimpse to the Repo itself. But we could add a Link to the Guidelines?

Thinking about it you're right. Let's keep it minimal. Good job! I'll merge in! Thank you 🤘🤘

**Review by pyymenta — APPROVED** [review]

**Pull request merged**
