### PR TITLE
JSON file of events and messages

### PR DESCRIPTION
**Pull request by danielskjo**
json file with events and messages

### CODE REVIEW

**Comment by pyymenta** [comment]
Hello @danieljo09,

Thank you for your contribuition. I have some points:

* JSON files must have `double quotes` instead of `single quotes`
* Can you add an `id` to the event? For example:

```
{
            "id": "wrong_trajectory",
            "event": "Ship goes more than 5 points to the left/right",
            "message": "wrong trajectory"
},
``` 

This will make easier to access the event :heavy_check_mark: 

* JSON files must have comma at the end of property, except the last one of the object. Example:

```
{
            "id": "wrong_trajectory",
            "event": "Ship goes more than 5 points to the left/right",
            "message": "wrong trajectory"
}
``` 

If you have some doubts, be sure to ask :smile_cat:

**Comment by danielskjo** [comment]
Thank you for the clarification! Sorry I'm learning a lot as I do these things..

**Comment by danielskjo** [comment]
Done!

**Comment by pyymenta** [comment]
Awesome!!!

Thank you for your contribution!! Feel free to contribute in our other issues!

I'll merge in!

**Comment by pyymenta** [comment]
It will closes #8

**Review by pyymenta — APPROVED** [review]

**Comment by danielskjo** [comment]
thanks for being understanding and clarifying for a beginner like me. I really appreciate it!

**Pull request merged**
