### PR TITLE
Rocket commands system, move and speed control

### LINKED ISSUE #3: Add commands using the keyboard A W S D
Add the I/O commands to the CLI!

Something like this:

Peek 2020-10-02 19-17

### PR DESCRIPTION
**Pull request by DanielVip3**
**CHANGELOG** :memo:

* Updated main.ts file with a new loop which prints movements and pressed keys
* Created CLI main class which binds keypress events and prints launch messages
* Created a KeyListener class which handles keypress and calls events from the CLI class
* Created a location interface with two existing locations (Earth and Moon)
* Updated Spacecraft class with speed, movement function and locations
* Updated start script in package.json

**PRINTS(OPTIONAL)** :framed_picture:

**LABELS**

* enhancement

Closes #3, #2, #1

### CODE REVIEW

**Comment by pyymenta** [comment]
Thank you so much for your contribution!

This changes conflicts with some files, we need to fix it before merge in.

The tests still running? I can't run now because I'm on a cellphone

**Comment by DanielVip3** [comment]
@pyymenta Thanks.
Yeah, I saw the conflict - the files conflicting are the dist compiled ones. I'll try running the tests and see.

**Comment by DanielVip3** [comment]
No, tests aren't working because they were based on the `createMessage` method of the Spacecraft class, which doesn't exist anymore.
I'll create a test which tests if the spacecraft's movement behaves correctly, and remove the previous test.

**Comment by DanielVip3** [comment]
I understood the conflict.
I don't know why you merged the other movement system though, when I said I was doing it. I'm gonna resolve conflicts, anyways.

**Comment by DanielVip3** [comment]
@pyymenta Conflicts fixed. The new movement system is inside this pull request, along with the new tests.

I think you can merge now.

**Review by pyymenta — APPROVED** [review]
Looks good to me :rocket: :rocket: :rocket: :rocket: 

Thank you! I'll merge your changes! 

Feel free to keep improving our rocket with your nice job! :clap: :clap: :clap:

**Pull request merged**
